name: Compile & Test

on: [push]

jobs:
  build:
    name: Compile binary
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - name: Setup test dependencies
        run: docker-compose up -d

      - name: Run unit tests
        run: go test ./...

      - name: Stop test dependencies
        run: docker-compose down
